name: run main.py

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 11-22 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push
      contents: write
      
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r toys/requirements_main.txt

      - name: install playwright
        run: |
          pip install playwright
          playwright install chromium
          
      - name: execute py script # run main.py
        #env:
          #SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python main.py

      - name: Notify Telegram on Failure
        if: failure() && secrets.TELEGRAM_BOT_TOKEN && secrets.TELEGRAM_CHAT_ID
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="⚠️ GitHub Actions failed for ${{ github.repository }} in the ${{ github.ref }} branch."

      - name: Notify Telegram on Success
        if: success() && secrets.TELEGRAM_BOT_TOKEN && secrets.TELEGRAM_CHAT_ID
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="✅ GitHub Actions succeeded for ${{ github.repository }} in the ${{ github.ref }} branch."

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "ELCANO" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
